In [1]:
import numpy as np
from scipy import linalg

In [3]:
B = np.array([[1, 0, 3, 0, 26],[0, 1, -2, 0, -8], [0, 0, 0, 1, 8]])
B

array([[ 1,  0,  3,  0, 26],
       [ 0,  1, -2,  0, -8],
       [ 0,  0,  0,  1,  8]])

In [6]:
u, s, vh = linalg.svd(B)

In [12]:
np.set_printoptions(2, suppress=True)

In [16]:
vh 

array([[ 0.03, -0.01,  0.12,  0.01,  0.99],
       [-0.02, -0.43,  0.81, -0.38, -0.09],
       [-0.4 , -0.6 ,  0.  ,  0.7 , -0.  ],
       [ 0.14,  0.57,  0.57,  0.57, -0.07],
       [-0.91,  0.36,  0.07, -0.21,  0.03]])

In [31]:
c1 = np.array([-3, 2, 1, 0,0])

In [32]:
B @ c1

array([0, 0, 0])

In [33]:
np.dot(B[0], c1)

0

In [34]:
B[0]

array([ 1,  0,  3,  0, 26])

In [35]:
c1

array([-3,  2,  1,  0,  0])

In [48]:
c2 = np.array([(-26 - 3 * (31/7)),39 - 31/7*5, 31/7, -8, 1])
c2

array([-39.29,  16.86,   4.43,  -8.  ,   1.  ])

In [49]:
B @ c1

array([0, 0, 0])

In [50]:
B @ c2

array([ 0., -0.,  0.])

In [51]:
c1

array([-3,  2,  1,  0,  0])

In [52]:
c2

array([-39.29,  16.86,   4.43,  -8.  ,   1.  ])

In [62]:
B @ vh.T

array([[26.19, -0.06, -0.4 ,  0.  , -0.  ],
       [-8.18, -1.29, -0.6 ,  0.  , -0.  ],
       [ 7.95, -1.14,  0.7 ,  0.  ,  0.  ]])